### ISSUE TITLE
Initializer does not respect Nx default backend

### ISSUE THREAD

**Issue by alisinabh** [elixir-nx/axon#517]
Hi,

I've tried using Torchx with mps backend on an M1 machine but I get the following error.

```
** (ArgumentError) cannot perform operation across devices mps and cpu
    (torchx 0.5.3) lib/torchx.ex:467: anonymous fn/2 in Torchx.prepare_tensors_list!/2
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (elixir 1.14.4) lib/enum.ex:1658: Enum."-map/2-lists^map/1-0-"/2
    (torchx 0.5.3) lib/torchx.ex:462: Torchx.prepare_tensors_list!/2
    (elixir 1.14.4) lib/enum.ex:1780: Enum."-map_reduce/3-lists^mapfoldl/2-0-"/3
    (torchx 0.5.3) lib/torchx.ex:244: Torchx.concatenate/2
    (torchx 0.5.3) lib/torchx/backend.ex:421: Torchx.Backend.concatenate/3
    (nx 0.5.3) lib/nx/defn/evaluator.ex:418: Nx.Defn.Evaluator.eval_apply/4
```

After some digging I found out that during initialization (probably bias initializer) there is a value being produced with BinaryBackend and Torchx will automatically backend copy to Torchex.Backend but it does not respect the default backend configuration and will copy to cpu instead of mps.

To reproduce you can run the following script
```elixir
Mix.install(
  [
    {:torchx, "~> 0.5.3"},
    {:axon, "~> 0.5.1"}
  ],
  config: [nx: [default_backend: {Torchx.Backend, device: :mps}]]
)

model =
  Axon.input("input")
  |> Axon.dense(1)

{init_fn, _predict_fn} = Axon.build(model, debug: true)

init_fn.(Nx.template({1, 1}, :f32), %{})
|> IO.inspect()
```

**Comment by polvalente** [comment]
I believe this is an issue in Torchx itself and not in Axon. The Axon initializers are in the end all implemented through Defn, so if the backend options aren't being fetched and passed on properly, chances are this is related to Torchx.

An easy way to test this is to use EXLA in a machine with cuda support and set the default backend to `{EXLA.Backend, client: :cuda}`.

**Comment by alisinabh** [comment]
Thanks @polvalente 

I have investigated this issue a bit more and it seems like in the initiation process a tensor is being created using `Nx.BinaryBacked` and then this tensor get's passed to [from_nx](https://github.com/elixir-nx/nx/blob/main/torchx/lib/torchx/backend.ex#L1808) function in Torchx.Backend. Now based on [torchx/backend.ex#L1808](https://github.com/elixir-nx/nx/blob/main/torchx/lib/torchx/backend.ex#L1808), Torchx will call `Nx.backend_transfer` but it does not know about the default options anymore and will create cpu tensor instead of mps or any other device that the user has specified.

I can see two possible solutions:

1. Investigate why the initializer is making a tensor in `Nx.BinaryBackend` and force it to use `Nx.default_backend` instead.
2. Create a new configuration parameter for Torchx which stores the default options for when the `from_nx` function wants to call `backend_transfer(tensor, {Torchx.Backend, default_options})` in [torchx/backend.ex#L1808](https://github.com/elixir-nx/nx/blob/main/torchx/lib/torchx/backend.ex#L1808)

**Comment by benswift** [comment]
I just ran into the same issue - did you ever try out either of your two proposed solutions?

**Comment by alisinabh** [comment]
Hi @benswift 

I actually changed a line in Torchex Backend to forcefully create tensors with the mps device for my test and it worked as expected.

But I don't yet understand why tensors are created in BinaryBackend in the first place...

**Comment by benswift** [comment]
Ah, ok, thanks for the update :)

**Comment by josevalim** [comment]
Yes, this is a torchx issue, so closing for now!
